'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { Activity, Bell, CalendarDays, ChevronDown, ChevronUp, Droplet, Heart, Info, Plus, Settings2, Sparkles, X } from 'lucide-react'
import { calculateCycleSummary, getAcceptedCareContext, getCareLogs, getCareReminders, getCycleSettings, getFertilityLabel, saveCareLog, saveCareReminder, saveCycleSettings, type CareDraft, type CareLog, type CareReminder, type CycleSettings } from '@/lib/care-data'

type Tab = 'today' | 'insights' | 'calendar' | 'reminders' | 'settings'
type Section = 'mood' | 'symptoms' | 'sex' | 'discharge' | 'digestion' | 'pregnancy_test' | 'ovulation_test' | 'contraceptives' | 'activities'
const sections: Array<{ id: Section; title: string; options: string[] }> = [
  { id: 'mood', title: 'Mood', options: ['Calm 😌', 'Happy 😊', 'Energetic ⚡', 'Frisky 😘', 'Mood swings 😵‍💫', 'Irritated 😡', 'Sad 😢', 'Anxious 😰'] },
  { id: 'symptoms', title: 'Symptoms', options: ['Everything is fine', 'Cramps', 'Tender breasts', 'Headache', 'Acne', 'Backache', 'Fatigue', 'Cravings', 'Insomnia', 'Abdominal pain', 'Hot flashes'] },
  { id: 'sex', title: 'Sex & sex drive', options: ["Didn't have sex", 'Protected sex', 'Unprotected sex', 'Oral sex', 'Anal sex', 'Masturbation', 'Sensual touch', 'Sex toys', 'Orgasm', 'No orgasm', 'High sex drive', 'Neutral sex drive', 'Low sex drive'] },
  { id: 'discharge', title: 'Discharge', options: ['No discharge', 'Creamy', 'Watery', 'Sticky', 'Egg white', 'Spotting', 'Unusual'] },
  { id: 'digestion', title: 'Digestion & stool', options: ['Nausea', 'Bloating', 'Constipation', 'Diarrhea'] },
  { id: 'pregnancy_test', title: 'Pregnancy test', options: ["Didn't take test", 'Positive', 'Negative', 'Faint line'] },
  { id: 'ovulation_test', title: 'Ovulation test', options: ["Didn't take test", 'Positive', 'Negative'] },
  { id: 'contraceptives', title: 'Contraceptives', options: ['Taken on time', "Yesterday's pill", 'Missed pill'] },
  { id: 'activities', title: 'Physical activity', options: ["Didn't exercise", 'Yoga', 'Gym', 'Aerobics & dancing', 'Swimming', 'Team sports', 'Running', 'Cycling', 'Walking'] },
]
const dateKey = (date: Date) => date.toISOString().slice(0, 10)
const formatDate = (value: string) => new Date(`${value}T12:00:00`).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })

export default function CarePage() {
  const [tab, setTab] = useState<Tab>('today')
  const [logs, setLogs] = useState<CareLog[]>([])
  const [settings, setSettings] = useState<CycleSettings | null>(null)
  const [context, setContext] = useState<{ userId: string; coupleId: string } | null>(null)
  const [loading, setLoading] = useState(true)
  const [logOpen, setLogOpen] = useState(false)
  const [calendarOpen, setCalendarOpen] = useState(false)
  const [initialSection, setInitialSection] = useState<Section | null>(null)
  const reload = async () => {
    setLoading(true)
    try { const next = await getAcceptedCareContext(); setContext(next); if (next) { const [nextLogs, nextSettings] = await Promise.all([getCareLogs(next.coupleId), getCycleSettings(next.coupleId)]); setLogs(nextLogs); setSettings(nextSettings) } } finally { setLoading(false) }
  }
  useEffect(() => { void reload() }, [])
  const summary = useMemo(() => calculateCycleSummary(logs, settings ?? { couple_id: '', cycle_length: 28, period_length: 5, last_period_start: null, updated_at: '' }), [logs, settings])
  const openLog = (section: Section | null = null) => { setInitialSection(section); setLogOpen(true) }
  const daysUntil = summary.nextPeriodStart ? Math.max(0, Math.ceil((new Date(`${summary.nextPeriodStart}T12:00:00`).getTime() - Date.now()) / 86400000)) : null

  if (loading) return <div className="flex min-h-[420px] items-center justify-center"><div className="h-9 w-9 animate-spin rounded-full border-2 border-[var(--accent-1)]/25 border-t-[var(--accent-1)]" /></div>
  if (!context || !settings) return <section className="glass-card mx-auto max-w-xl p-7 text-center"><Heart className="mx-auto h-8 w-8 text-[var(--accent-1)]" /><h1 className="mt-3 text-2xl text-[var(--text-primary)]">Cycle Care is shared</h1><p className="mt-2 text-sm text-[var(--text-secondary)]">Accept your couple link before creating shared cycle records.</p></section>

  const tabs: Array<{ id: Tab; label: string; icon: typeof Sparkles }> = [{ id: 'today', label: 'Today', icon: Sparkles }, { id: 'insights', label: 'Insights', icon: Activity }, { id: 'calendar', label: 'Calendar', icon: CalendarDays }, { id: 'reminders', label: 'Reminders', icon: Bell }, { id: 'settings', label: 'Settings', icon: Settings2 }]
  return <div className="mx-auto max-w-5xl space-y-5 pb-8">
    <header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.22em] text-[var(--text-secondary)]">Shared Cycle Care</p><h1 className="mt-1 text-3xl text-[var(--text-primary)]">Cycle Care</h1></div><button onClick={() => openLog()} className="glass-button inline-flex items-center gap-2 px-4 py-2.5 text-sm font-semibold"><Plus className="h-4 w-4" />Log today</button></header>
    <nav className="flex gap-2 overflow-x-auto pb-1">{tabs.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => id === 'calendar' ? setCalendarOpen(true) : setTab(id)} className={`inline-flex shrink-0 items-center gap-2 rounded-full border px-4 py-2 text-sm ${tab === id && id !== 'calendar' ? 'border-[var(--accent-1)]/50 bg-[var(--accent-1)]/15 text-[var(--accent-1)]' : 'border-white/10 bg-[var(--card-bg)] text-[var(--text-secondary)]'}`}><Icon className="h-4 w-4" />{label}</button>)}</nav>
    {tab === 'today' && <Today summary={summary} daysUntil={daysUntil} onLogPeriod={() => setCalendarOpen(true)} onOpen={openLog} onInsights={() => setTab('insights')} onReminders={() => setTab('reminders')} logs={logs} />}
    {tab === 'insights' && <Insights logs={logs} summary={summary} />}
    {tab === 'reminders' && <Reminders coupleId={context.coupleId} userId={context.userId} />}
    {tab === 'settings' && <CycleSettings settings={settings} logs={logs} onSave={async (next) => { await saveCycleSettings({ ...next, couple_id: context.coupleId }); await reload() }} />}
    {logOpen && <DailyLog log={logs.find((entry) => entry.log_date === dateKey(new Date()))} initial={initialSection} onClose={() => setLogOpen(false)} onSave={async (draft) => { await saveCareLog(context.coupleId, context.userId, draft); setLogOpen(false); await reload() }} />}
    {calendarOpen && <PeriodCalendarModal logs={logs} summary={summary} onClose={() => setCalendarOpen(false)} onSave={async (selected) => {
      const selectedDays = new Set(selected)
      const periodLogs = logs.filter((log) => log.period_day)
      for (const day of selectedDays) {
        const current = logs.find((log) => log.log_date === day)
        await saveCareLog(context.coupleId, context.userId, { log_date: day, period_day: true, symptoms: current?.symptoms ?? [] })
      }
      for (const log of periodLogs.filter((entry) => !selectedDays.has(entry.log_date))) {
        await saveCareLog(context.coupleId, context.userId, { log_date: log.log_date, period_day: false, symptoms: log.symptoms })
      }
      setCalendarOpen(false); await reload()
    }} />}
  </div>
}

function Today({ summary, daysUntil, onLogPeriod, onOpen, onInsights, onReminders, logs }: { summary: ReturnType<typeof calculateCycleSummary>; daysUntil: number | null; onLogPeriod: () => void; onOpen: (section: Section | null) => void; onInsights: () => void; onReminders: () => void; logs: CareLog[] }) {
  const days = Array.from({ length: 7 }, (_, index) => { const day = new Date(); day.setDate(day.getDate() - day.getDay() + index); return day })
  const actions: Array<{ Icon: typeof Droplet; label: string; action: () => void }> = [{ Icon: Droplet, label: 'Log period', action: onLogPeriod }, { Icon: Plus, label: 'Symptoms', action: () => onOpen('symptoms') }, { Icon: Heart, label: 'Intimacy', action: () => onOpen('sex') }]
  return <div className="space-y-5"><section className="glass-card p-3"><div className="grid grid-cols-7 gap-1">{days.map((day) => <button key={day.toISOString()} onClick={onLogPeriod} className={`rounded-2xl py-2 text-center ${dateKey(day) === dateKey(new Date()) ? 'bg-[var(--accent-1)]/15 text-[var(--accent-1)]' : 'text-[var(--text-secondary)]'}`}><span className="block text-[10px] uppercase">{day.toLocaleDateString(undefined, { weekday: 'narrow' })}</span><span className="mt-1 flex h-8 w-8 items-center justify-center rounded-full text-sm font-semibold mx-auto">{day.getDate()}</span></button>)}</div></section>
    <section className="glass-card relative overflow-hidden p-7 text-center"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,var(--accent-1),transparent_55%)] opacity-15" /><div className="relative"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[var(--text-secondary)]">Today&apos;s cycle</p><h2 className="mt-3 text-5xl text-[var(--accent-2)]">{daysUntil === null ? '—' : `Period in ${daysUntil} days`}</h2><p className="mt-4 text-sm text-[var(--text-secondary)]">{getFertilityLabel(summary)} · predictions are not medical advice</p>{!summary.regular && <p className="mt-2 text-xs text-amber-300">Recent cycles vary, so this estimate may be less accurate.</p>}</div></section>
    <section className="grid grid-cols-3 gap-3">{actions.map(({ Icon, label, action }) => <button key={label} onClick={action} className="flex flex-col items-center gap-2 py-2 text-sm text-[var(--text-secondary)]"><span className="flex h-16 w-16 items-center justify-center rounded-full border border-[var(--accent-1)]/40 bg-[var(--card-bg)] text-[var(--accent-1)] shadow-[0_0_22px_color-mix(in_srgb,var(--accent-1)_25%,transparent)]"><Icon className="h-7 w-7" /></span>{label}</button>)}</section>
    <section><div className="mb-3 flex items-center justify-between"><h2 className="text-xl text-[var(--text-primary)]">My daily insights</h2><button onClick={onInsights} className="text-sm text-[var(--accent-1)]">See all</button></div><div className="grid gap-3 md:grid-cols-2"><InfoCard title="Cycle day" body={summary.day ? `Day ${summary.day} of an estimated ${summary.cycleLength}-day cycle.` : 'Log your period to begin your estimate.'} /><InfoCard title="Shared check-in" body={logs.length ? `${logs.length} shared Care days recorded together.` : 'Your first shared check-in starts the timeline.'} /></div></section>
    <section className="glass-card p-5"><div className="flex items-center justify-between"><h2 className="text-xl text-[var(--text-primary)]">Cycle history</h2><span className="text-sm text-[var(--accent-1)]">Shared</span></div><div className="mt-4 flex gap-1">{Array.from({ length: summary.cycleLength }, (_, index) => <span key={index} className={`h-3 flex-1 rounded-full ${index < summary.periodLength ? 'bg-[var(--accent-1)]' : summary.day !== null && index >= summary.cycleLength - 19 && index <= summary.cycleLength - 13 ? 'bg-emerald-400' : 'bg-white/10'}`} />)}</div><div className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><p className="text-[var(--text-secondary)]">Average cycle</p><p className="mt-1 text-xl text-[var(--text-primary)]">{summary.cycleLength} days</p></div><div><p className="text-[var(--text-secondary)]">Next period</p><p className="mt-1 font-semibold text-[var(--text-primary)]">{summary.nextPeriodStart ? formatDate(summary.nextPeriodStart) : 'Not available'}</p></div></div></section>
    <button onClick={onReminders} className="glass-card flex w-full items-center gap-3 p-4 text-left"><Bell className="h-5 w-5 text-[var(--accent-1)]" /><span><strong className="block text-[var(--text-primary)]">Smart reminders</strong><small className="text-[var(--text-secondary)]">Period, fertile, and daily check-in alerts</small></span></button></div>
}
function InfoCard({ title, body }: { title: string; body: string }) { return <div className="glass-card p-4"><p className="font-semibold text-[var(--text-primary)]">{title}</p><p className="mt-1 text-sm leading-6 text-[var(--text-secondary)]">{body}</p></div> }

function DailyLog({ log, initial, onClose, onSave }: { log?: CareLog; initial: Section | null; onClose: () => void; onSave: (draft: CareDraft) => Promise<void> }) {
  const [draft, setDraft] = useState<CareDraft>(() => ({ log_date: dateKey(new Date()), mood: log?.mood ?? null, symptoms: log?.symptoms ?? [], sex: log?.sex ?? [], discharge: log?.discharge ?? [], digestion: log?.digestion ?? [], pregnancy_test: log?.pregnancy_test ?? [], ovulation_test: log?.ovulation_test ?? null, contraceptives: log?.contraceptives ?? [], other_pills: log?.other_pills ?? [], activities: log?.activities ?? [], water_intake: log?.water_intake ?? 0, weight: log?.weight ?? null, basal_temp: log?.basal_temp ?? null, notes: log?.notes ?? '' }))
  const [closed, setClosed] = useState<Set<string>>(new Set(sections.filter((section) => section.id !== initial).map((section) => section.id)))
  const [saving, setSaving] = useState(false)
  const toggle = (field: Section, value: string) => setDraft((current) => {
    if (field === 'mood') return { ...current, mood: current.mood === value ? null : value }
    if (field === 'ovulation_test') return { ...current, ovulation_test: current.ovulation_test === value ? null : value }
    const values = (current[field] as string[] | undefined) ?? []
    return { ...current, [field]: values.includes(value) ? values.filter((item) => item !== value) : [...values, value] }
  })
  return <div className="fixed inset-0 z-50"><button aria-label="Close log" onClick={onClose} className="absolute inset-0 bg-black/60 backdrop-blur-sm" /><aside className="absolute inset-y-0 right-0 flex w-full max-w-lg flex-col border-l border-white/10 bg-[var(--bg-2)] shadow-2xl"><header className="flex items-center justify-between border-b border-white/10 p-5"><div><h2 className="text-xl text-[var(--text-primary)]">Daily Log</h2><p className="text-sm text-[var(--text-secondary)]">{new Date().toLocaleDateString()}</p></div><button onClick={onClose} className="rounded-full bg-white/10 p-2 text-[var(--text-primary)]"><X className="h-5 w-5" /></button></header><div className="flex-1 overflow-y-auto p-4"><div className="space-y-3">{sections.map((section) => { const isClosed = closed.has(section.id); const chosen = section.id === 'mood' ? (draft.mood ? [draft.mood] : []) : section.id === 'ovulation_test' ? (draft.ovulation_test ? [draft.ovulation_test] : []) : ((draft[section.id] as string[] | undefined) ?? []); return <section key={section.id} className="glass-card overflow-hidden"><button onClick={() => setClosed((current) => { const next = new Set(current); next.has(section.id) ? next.delete(section.id) : next.add(section.id); return next })} className="flex w-full items-center justify-between p-4"><span className="font-semibold text-[var(--text-primary)]">{section.title}{chosen.length ? <small className="ml-2 rounded-full bg-[var(--accent-1)]/15 px-2 py-0.5 text-[var(--accent-1)]">{chosen.length}</small> : null}</span>{isClosed ? <ChevronDown className="h-4 w-4" /> : <ChevronUp className="h-4 w-4" />}</button>{!isClosed && <div className="flex flex-wrap gap-2 px-4 pb-4">{section.options.map((option) => <button key={option} onClick={() => toggle(section.id, option)} className={`rounded-full border px-3 py-2 text-sm transition ${chosen.includes(option) ? 'border-[var(--accent-1)] bg-[var(--accent-1)]/15 text-[var(--accent-1)]' : 'border-white/10 bg-white/5 text-[var(--text-secondary)]'}`}>{option}</button>)}</div>}</section> })}
    <section className="glass-card grid gap-3 p-4 sm:grid-cols-3"><label className="text-sm text-[var(--text-secondary)]">Water (ml)<input type="number" min="0" value={draft.water_intake ?? 0} onChange={(event) => setDraft({ ...draft, water_intake: Number(event.target.value) })} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 p-2 text-[var(--text-primary)]" /></label><label className="text-sm text-[var(--text-secondary)]">Weight (kg)<input type="number" step="0.1" value={draft.weight ?? ''} onChange={(event) => setDraft({ ...draft, weight: event.target.value ? Number(event.target.value) : null })} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 p-2 text-[var(--text-primary)]" /></label><label className="text-sm text-[var(--text-secondary)]">Basal temp (°C)<input type="number" step="0.1" value={draft.basal_temp ?? ''} onChange={(event) => setDraft({ ...draft, basal_temp: event.target.value ? Number(event.target.value) : null })} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 p-2 text-[var(--text-primary)]" /></label></section><section className="glass-card p-4"><label className="text-sm font-semibold text-[var(--text-primary)]">Notes<textarea value={draft.notes ?? ''} onChange={(event) => setDraft({ ...draft, notes: event.target.value })} placeholder="How have you been feeling?" className="mt-3 min-h-24 w-full rounded-xl border border-white/10 bg-white/5 p-3 text-sm text-[var(--text-primary)]" /></label></section></div></div><footer className="border-t border-white/10 p-4"><button disabled={saving} onClick={async () => { setSaving(true); try { await onSave(draft) } finally { setSaving(false) } }} className="glass-button w-full py-3 font-semibold">{saving ? 'Saving…' : 'Save shared daily log'}</button></footer></aside></div>
}

function PeriodCalendarModal({ logs, summary, onClose, onSave }: { logs: CareLog[]; summary: ReturnType<typeof calculateCycleSummary>; onClose: () => void; onSave: (dates: string[]) => Promise<void> }) {
  const existing = useMemo(() => new Set(logs.filter((log) => log.period_day).map((log) => log.log_date)), [logs])
  const [selected, setSelected] = useState<Set<string>>(existing)
  const [saving, setSaving] = useState(false)
  const months = useMemo(() => Array.from({ length: 14 }, (_, index) => new Date(new Date().getFullYear(), new Date().getMonth() - 6 + index, 1)), [])
  const currentMonth = useRef<HTMLDivElement>(null)
  useEffect(() => { currentMonth.current?.scrollIntoView({ block: 'start' }) }, [])
  const toggle = (value: string) => setSelected((current) => { const next = new Set(current); next.has(value) ? next.delete(value) : next.add(value); return next })
  return <div className="fixed inset-0 z-50"><button onClick={onClose} aria-label="Close period calendar" className="absolute inset-0 bg-black/60 backdrop-blur-sm" /><section className="absolute inset-x-0 bottom-0 mx-auto flex max-h-[90vh] max-w-2xl flex-col rounded-t-[2rem] border border-white/10 bg-[var(--bg-2)]"><header className="flex items-center justify-between p-5"><div><h2 className="text-2xl text-[var(--text-primary)]">Log Period</h2><p className="mt-1 text-sm text-[var(--text-secondary)]">Scroll up or down; this month and next month open first.</p></div><button onClick={onClose} className="rounded-full bg-white/10 p-2"><X className="h-5 w-5" /></button></header><div className="overflow-y-auto px-5 pb-4"><div className="grid gap-6 md:grid-cols-2">{months.map((month) => <div key={month.toISOString()} ref={month.getMonth() === new Date().getMonth() && month.getFullYear() === new Date().getFullYear() ? currentMonth : undefined}><MonthGrid month={month} selected={selected} summary={summary} onToggle={toggle} /></div>)}</div></div><footer className="sticky bottom-0 border-t border-white/10 bg-[var(--bg-2)] p-4"><div className="mb-3 flex flex-wrap gap-3 text-xs text-[var(--text-secondary)]"><span>● <b className="text-[var(--accent-1)]">Period</b></span><span>○ <b className="text-emerald-400">Fertile estimate</b></span><span>● Today</span></div><button disabled={saving} onClick={async () => { setSaving(true); try { await onSave([...selected]) } finally { setSaving(false) } }} className="glass-button w-full py-3 font-semibold">{saving ? 'Saving…' : 'Save period dates'}</button></footer></section></div>
}
function MonthGrid({ month, selected, summary, onToggle }: { month: Date; selected: Set<string>; summary: ReturnType<typeof calculateCycleSummary>; onToggle: (value: string) => void }) { const days = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); const leading = new Date(month.getFullYear(), month.getMonth(), 1).getDay(); const today = dateKey(new Date()); return <section><h3 className="mb-3 text-center text-lg text-[var(--text-primary)]">{month.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</h3><div className="grid grid-cols-7 gap-1 text-center text-xs text-[var(--text-secondary)]">{['S', 'M', 'T', 'W', 'T', 'F', 'S'].map((day, index) => <span key={`${day}-${index}`}>{day}</span>)}{Array.from({ length: leading }).map((_, index) => <span key={`empty-${index}`} />)}{Array.from({ length: days }, (_, index) => { const current = new Date(month.getFullYear(), month.getMonth(), index + 1); const value = dateKey(current); const isSelected = selected.has(value); const fertile = summary.fertileStart && summary.fertileEnd && value >= summary.fertileStart && value <= summary.fertileEnd; return <button key={value} onClick={() => onToggle(value)} className={`mx-auto flex h-9 w-9 items-center justify-center rounded-full text-sm transition ${isSelected ? 'bg-[var(--accent-1)] text-white' : value === today ? 'border border-[var(--accent-2)] text-[var(--accent-2)]' : fertile ? 'border border-emerald-400 text-emerald-300' : 'text-[var(--text-primary)] hover:bg-white/10'}`}>{index + 1}</button> })}</div></section> }

function Insights({ logs, summary }: { logs: CareLog[]; summary: ReturnType<typeof calculateCycleSummary> }) { const moods = logs.reduce<Record<string, number>>((all, log) => { if (log.mood) all[log.mood] = (all[log.mood] ?? 0) + 1; return all }, {}); const symptoms = logs.flatMap((log) => log.symptoms ?? []).reduce<Record<string, number>>((all, item) => { all[item] = (all[item] ?? 0) + 1; return all }, {}); const moodEntries = Object.entries(moods).sort((a, b) => b[1] - a[1]); const symptomEntries = Object.entries(symptoms).sort((a, b) => b[1] - a[1]).slice(0, 8); return <div className="space-y-4"><section className="glass-card p-5"><h2 className="text-2xl text-[var(--text-primary)]">Insights & trends</h2><p className="mt-1 text-sm text-[var(--text-secondary)]">Your shared check-ins, shown as gentle patterns—not medical conclusions.</p></section><Stats title="Mood this month" items={moodEntries} empty="No mood entries yet. Use the daily log to start." /><Stats title="Most common symptoms" items={symptomEntries} empty="No symptom entries yet." /><section className="glass-card grid gap-4 p-5 sm:grid-cols-3">{[['Average', `${summary.cycleLength} days`], ['Cycle range', summary.regular ? 'Regular pattern' : 'Varies recently'], ['Period length', `${summary.periodLength} days`]].map(([label, value]) => <div key={label}><p className="text-sm text-[var(--text-secondary)]">{label}</p><p className="mt-1 text-lg text-[var(--text-primary)]">{value}</p></div>)}</section></div> }
function Stats({ title, items, empty }: { title: string; items: Array<[string, number]>; empty: string }) { const highest = Math.max(...items.map(([, count]) => count), 1); return <section className="glass-card p-5"><h2 className="text-xl text-[var(--text-primary)]">{title}</h2>{items.length ? <div className="mt-4 space-y-3">{items.map(([label, count]) => <div key={label} className="flex items-center gap-3"><span className="w-28 truncate text-sm text-[var(--text-secondary)]">{label}</span><span className="h-2 flex-1 overflow-hidden rounded-full bg-white/10"><span className="block h-full rounded-full bg-[var(--accent-1)]" style={{ width: `${count / highest * 100}%` }} /></span><span className="w-8 text-right text-sm text-[var(--text-primary)]">{count}</span></div>)}</div> : <p className="mt-3 text-sm text-[var(--text-secondary)]">{empty}</p>}</section> }

function Reminders({ coupleId, userId }: { coupleId: string; userId: string }) {
  const [enabled, setEnabled] = useState<Record<CareReminder['reminder_type'], boolean>>({ pms: false, period: false, fertile: false, symptom: false })
  const [saving, setSaving] = useState<string | null>(null)
  useEffect(() => { void getCareReminders(coupleId).then((records) => setEnabled((current) => records.reduce((next, record) => ({ ...next, [record.reminder_type]: record.enabled }), current))).catch(() => undefined) }, [coupleId])
  const toggle = async (key: CareReminder['reminder_type']) => {
    const next = !enabled[key]
    if (next && 'Notification' in window && Notification.permission === 'default') await Notification.requestPermission()
    setSaving(key)
    try { await saveCareReminder(coupleId, userId, key, next); setEnabled((current) => ({ ...current, [key]: next })) } finally { setSaving(null) }
  }
  const options: Array<[CareReminder['reminder_type'], string, string]> = [['pms', 'PMS reminder', '5–7 days before an expected period'], ['period', 'Period reminder', '1 day before expected period'], ['fertile', 'Fertile window alert', 'When the estimated fertile window begins'], ['symptom', 'Daily check-in', 'A gentle prompt to log symptoms']]
  return <section className="glass-card p-5"><div className="flex items-center gap-3"><Bell className="h-6 w-6 text-[var(--accent-1)]" /><div><h2 className="text-xl text-[var(--text-primary)]">Smart reminders</h2><p className="text-sm text-[var(--text-secondary)]">Reminder choices are shared; browser permission remains per device.</p></div></div><div className="mt-5 space-y-3">{options.map(([key, title, note]) => <label key={key} className="flex items-center justify-between rounded-2xl bg-white/5 p-4"><span><strong className="block text-[var(--text-primary)]">{title}</strong><small className="text-[var(--text-secondary)]">{note}</small></span><input aria-label={title} disabled={saving === key} type="checkbox" checked={enabled[key]} onChange={() => void toggle(key)} className="h-5 w-5 accent-[var(--accent-1)]" /></label>)}</div></section>
}

function CycleSettings({ settings, logs, onSave }: { settings: CycleSettings; logs: CareLog[]; onSave: (settings: Omit<CycleSettings, 'couple_id' | 'updated_at'>) => Promise<void> }) { const [draft, setDraft] = useState({ cycle_length: settings.cycle_length, period_length: settings.period_length, last_period_start: settings.last_period_start ?? '' }); const [saving, setSaving] = useState(false); return <section className="glass-card max-w-2xl p-5"><div className="flex items-center gap-3"><Settings2 className="h-6 w-6 text-[var(--accent-1)]" /><div><h2 className="text-xl text-[var(--text-primary)]">Cycle settings</h2><p className="text-sm text-[var(--text-secondary)]">These shared settings improve estimates when history is limited.</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><label className="text-sm text-[var(--text-secondary)]">Average cycle (days)<input type="number" min="15" max="60" value={draft.cycle_length} onChange={(event) => setDraft({ ...draft, cycle_length: Number(event.target.value) })} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 p-3 text-[var(--text-primary)]" /></label><label className="text-sm text-[var(--text-secondary)]">Period length (days)<input type="number" min="1" max="14" value={draft.period_length} onChange={(event) => setDraft({ ...draft, period_length: Number(event.target.value) })} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 p-3 text-[var(--text-primary)]" /></label><label className="text-sm text-[var(--text-secondary)]">Last period start<input type="date" value={draft.last_period_start} onChange={(event) => setDraft({ ...draft, last_period_start: event.target.value })} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 p-3 text-[var(--text-primary)]" /></label></div><p className="mt-4 text-sm text-[var(--text-secondary)]">{logs.filter((log) => log.period_day).length >= 2 ? 'Recent period history will also be used to improve this estimate.' : 'Log at least 2–3 periods for a more personalized estimate.'}</p><button disabled={saving} onClick={async () => { setSaving(true); try { await onSave({ ...draft, last_period_start: draft.last_period_start || null }) } finally { setSaving(false) } }} className="glass-button mt-5 px-5 py-3">{saving ? 'Saving…' : 'Save shared settings'}</button></section> }
